// Barrel for the Fork-style git dialogs. Each is a presentational component:
// controlled open state in, typed payload out on submit.

export { AddRepositoryDialog } from "./AddRepositoryDialog"
export { BisectStartDialog } from "./BisectStartDialog"
export type { BisectStartPayload } from "./BisectStartDialog"
export { NewBranchDialog } from "./NewBranchDialog"
export type { LocalChangesMode, NewBranchPayload } from "./NewBranchDialog"
export { TagDialog } from "./TagDialog"
export type { TagPayload } from "./TagDialog"
export { RenameDialog } from "./RenameDialog"
export type { RenamePayload } from "./RenameDialog"
export { RewordDialog } from "./RewordDialog"
export type { RewordPayload } from "./RewordDialog"
export { InteractiveRebaseDialog } from "./InteractiveRebaseDialog"
export type { RebaseRowAction } from "./InteractiveRebaseDialog"
export { ResetDialog } from "./ResetDialog"
export type { ResetMode, ResetPayload } from "./ResetDialog"
export { StashApplyDialog } from "./StashApplyDialog"
export type { StashApplyPayload } from "./StashApplyDialog"
export { MergeDialog } from "./MergeDialog"
export type { MergePayload } from "./MergeDialog"
export { BranchMergeChooserDialog } from "./BranchMergeChooserDialog"
export type { BranchMergeChoice } from "./BranchMergeChooserDialog"
export { RevertParentDialog } from "./RevertParentDialog"
export type { RevertParentPayload } from "./RevertParentDialog"
export { DeleteDialog } from "./DeleteDialog"
export { DeleteTagDialog } from "./DeleteTagDialog"
export { DropDialog } from "./DropDialog"
export { ConfirmDialog } from "./ConfirmDialog"
